### ISSUE TITLE
use new RESTful interface

### ISSUE THREAD

**Issue by WolfgangFahl** [Paul-469/SPP-Knowledge-Graphs#1]
e.g. 
https://conferencecorpus.bitplan.com/eventseries/WEBIST?format=json

**Comment by Paul-469** [comment]
Project now uses RESTful interface.

**Comment by Paul-469** [comment]
[The commit](https://github.com/Paul-469/SPP-Knowledge-Graphs/commit/55a60bd5c69e511cae8497f70a76f65c098198ff)

**Comment by WolfgangFahl** [comment]
@Paul-469  thx
